### ISSUE TITLE
pmpro_level_expiration_text filter doesn't seem to work with this add on

### ISSUE THREAD

**Issue by rweaver-core** [strangerstudios/pmpro-set-expiration-dates#40] opened 2023-03-07 21:21 UTC
I am attempting to customize the expiration text for the levels using the pmpro_level_expiration_text filter and the text does not get updated when the add on is activated. I used code examples from https://gist.github.com/strangerstudios/9936197?permalink_comment_id=3593947 and https://gist.github.com/andrewlimaza/1a28067d55bf90ab084013f4de450233

**To Reproduce**
1. From the customization add on, create a function to modify the expiration text
2. Upload the add on
3. Set Expiration Date on level to be something, I used "Y2-03-31"
4. Look at membership-levels page to see standard/default expiration text
5. Deactivate Set Expiration Dates Add On
6. Look at membership-levels page to see desired expiration text

**Expected behavior**
Expected the expiration text to be updated to reflect desired text from function

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
Wordpress v 6.1.1
Paid Memberships Pro v 2.10.3
PHP v 7.4.29

**Comment by andrewlimaza** [comment] 2024-04-24 11:45
Thanks for reaching out @rweaver-core, I'm not sure if you figured this out already. The Set Expiration Date logic will need to be merged into your custom function to get the date value of the expiration if you wanted to merge a custom expiration text AND have the set expiry date. 

This Add On also filters the expiration text using the same hooks and sometimes code may compete and not work as intended or be overwritten depending on the priority of your functions. I did test this and the custom code snippet would override the Set Expiration Date text because the custom function is running later (and taking over).

We do not actively monitor GitHub for support requests. If you still need help with this, please can you open a support ticket on www.paidmembershipspro.com/support and we will continue to assist you.

**Closed by andrewlimaza** 2024-04-24 11:45 UTC
